package config

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// EnvFilePath returns the path to the conclave .env file
// This is a variable to allow testing
var EnvFilePath = func() (string, error) {
	configDir := os.Getenv("XDG_CONFIG_HOME")
	if configDir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("get home dir: %w", err)
		}
		configDir = filepath.Join(home, ".config")
	}
	return filepath.Join(configDir, "conclave", ".env"), nil
}

// LoadEnvFile loads environment variables from ~/.config/conclave/.env
// It does not override existing environment variables.
func LoadEnvFile() error {
	path, err := EnvFilePath()
	if err != nil {
		return err
	}

	// Also check for .env in current directory (project overrides)
	paths := []string{path}
	if cwd, err := os.Getwd(); err == nil {
		paths = append(paths, filepath.Join(cwd, ".env"))
	}

	for _, p := range paths {
		if err := loadEnvFromFile(p, false); err != nil && !os.IsNotExist(err) {
			return err
		}
	}

	return nil
}

// loadEnvFromFile reads a .env file and sets environment variables
func loadEnvFromFile(path string, override bool) error {
	file, err := os.Open(path)
	if err != nil {
		return err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Parse KEY=value
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])

		// Remove quotes if present
		if len(value) >= 2 {
			if (value[0] == '"' && value[len(value)-1] == '"') ||
				(value[0] == '\'' && value[len(value)-1] == '\'') {
				value = value[1 : len(value)-1]
			}
		}

		// Don't override existing env vars unless requested
		if !override && os.Getenv(key) != "" {
			continue
		}

		os.Setenv(key, value)
	}

	return scanner.Err()
}

// SaveEnvFile writes API keys to ~/.config/conclave/.env
func SaveEnvFile(keys map[string]string) error {
	path, err := EnvFilePath()
	if err != nil {
		return err
	}

	// Ensure directory exists
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	// Load existing keys (preserve any we're not updating)
	existing := make(map[string]string)
	if file, err := os.Open(path); err == nil {
		scanner := bufio.NewScanner(file)
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			parts := strings.SplitN(line, "=", 2)
			if len(parts) == 2 {
				existing[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
			}
		}
		file.Close()
	}

	// Merge new keys
	for k, v := range keys {
		if v != "" {
			existing[k] = v
		}
	}

	// Write file with restricted permissions
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("create env file: %w", err)
	}
	defer file.Close()

	fmt.Fprintln(file, "# Conclave API Keys")
	fmt.Fprintln(file, "# Generated by: conclave init")
	fmt.Fprintln(file, "")

	// Write in consistent order
	keyOrder := []string{
		"GEMINI_API_KEY",
		"OPENAI_API_KEY",
		"ANTHROPIC_API_KEY",
		"PERPLEXITY_API_KEY",
		"XAI_API_KEY",
		"ZHIPU_API_KEY",
	}

	for _, key := range keyOrder {
		if val, ok := existing[key]; ok && val != "" {
			fmt.Fprintf(file, "%s=%s\n", key, val)
		}
	}

	// Write any other keys not in our standard order
	for key, val := range existing {
		found := false
		for _, k := range keyOrder {
			if k == key {
				found = true
				break
			}
		}
		if !found && val != "" {
			fmt.Fprintf(file, "%s=%s\n", key, val)
		}
	}

	return nil
}
